### ISSUE TITLE
Alternative to CAP_ADD for Swarm users?

### ISSUE THREAD

**Issue by Spass1966** [key-networks/ztncui-containerized#10]
Based on @mark-stopka dropping a compose declaration I came up with this:
```
version: '3.7'
services:
  ztncui:
    container_name: ztncui
    image: keynetworks/ztncui
    volumes:
      ztncui:/opt/key-networks/ztncui/etc/
      zt1:/var/lib/zerotier-one/
    ports:
      3443:3443
    expose:
      3000:3000
    environment:
      HTTPS_PORT: 3000
      HTTP_PORT: 3443
      HTTP_ALL_INTERFACES: "yes"
    deploy:
      replicas: 5
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-falure
     networks:
       backend

volumes:
  ztncui:
  zt1:

networks:
  frontend:
  backend:
```
Does that look right, since Swarms cannot make use of CAP_ADD?

**Comment by key-networks** [comment]
It looks reasonable to me, but I have no experience with setting up swarms.

**Comment by Spass1966** [comment]
@key-networks I will try it out tomorrow and report back! 🙂

**Comment by Spass1966** [comment]
@mark-stopka if you care to take a look and critique I'd really appreciate it!

**Comment by Spass1966** [comment]
I really overcomplicated this. There doesn't appear to be any need for `CAP_ADD: NET_ADMIN` and I'm not sure why it's included in the official instructions. Additionally, no amount of futzing with environment variables or open ports allowed me to access the controller UI over HTTP. I had to access over HTTPS.

This was my final declaration in the end should other face the same confusion I did:
```
version: '3.7'
services:

  ztncui:
    image: keynetworks/ztncui
    volumes:
      - ztncui:/opt/key-networks/ztncui/etc/
      - zt1:/var/lib/zerotier-one/
    ports:
      - 3443:3443
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
    networks:
      - backend

volumes:
  ztncui:
  zt1:

networks:
  frontend:
  backend:
```
