### ISSUE TITLE
How to switch from mdPlusPlus to key-networks docker iamge

### ISSUE THREAD

**Issue by ovizii** [key-networks/ztncui-containerized#20]
I have been running this image: https://gist.github.com/mdPlusPlus/0f6285c6402aa4aff4aa4a9e5dfc38c0 

with this docker-compose file:

```
version: '3'

services:
  ztncui:
    image: mdplusplus/zerotier-network-controller-ui
    container_name: ztncui
    hostname: ztncui
    network_mode: bridge
    restart: "no"
    ports:
      - "3443:3443"
    volumes:
    - './ui:/opt/ztncui/src/etc'
    - './zt:/var/lib/zerotier-one'
```
simply switching the image to
`image: keynetworks/ztncui:latest`
results in me not being able to login via the web interface so I assume something has to be changed with the volumes?
