### ISSUE TITLE
Cannot run without HTTPS errors (Error: ENOENT: no such file or directory, open 'etc/tls/fullchain.pem')

### ISSUE THREAD

**Issue by jbcpollak** [key-networks/ztncui-containerized#6]
Hello,

I'm trying to run the container on an Intel-based Synology with Docker installed. When I try and run it I originally was getting errors about not having permissions to write to the mapped ztncui directory, until I gave that directory read/write permissions for everyone. I think this is because the docker images executes `sudo -u ztncui` but that user doesn't exist on the host system. I'm not even sure what that user id should be.

After I granted global write permissions, I got the error `Error: ENOENT: no such file or directory, open 'etc/tls/fullchain.pem'`. I want to run HTTP-only in the container, and then use the Synology to do HTTPS reverse proxy, but it seems like the container can't support that?

**Comment by key-networks** [comment]
Sorry, I don't have a Synology to test with.  Maybe you could try running the node.js code directly - see https://github.com/key-networks/ztncui

**Comment by jbcpollak** [comment]
@key-networks - sorry, I wasn't expecting you had a Synology, I was more wondering if there was a way to configure the docker container to disable HTTPS entirely so it wouldn't try and listen with encryption.

IE, I didn't see a way to do (effectively) `HTTPS_ENABLED=false` via the container.

That _should_ solve my problem.

About sudo, could the shell script be extended to sudo/or not based on an environment variable?

**Comment by jbcpollak** [comment]
Hello, I got this working with a few tweaks as described above (changes here https://github.com/jbcpollak/ztncui-containerized) and I needed to manually setup the `/etc` directory with the needed storage and tls directories, and the passwd file.

Is it possible to use the zerotier-one instance running inside the container to get the docker host onto the ZT network?

**Comment by key-networks** [comment]
I would imagine so.  Have you tried it?

**Comment by mark-stopka** [comment]
I am having the same issue, but running on a CentOS host with Traefik doing the proxying.

**Comment by mark-stopka** [comment]
There are several issues when deploying via docker using volumes, and behind proxy, the exec.sh needs to be completely re-written, ugly hack I came up with was:

```
version: '3.7'

networks:
  traefik_backend:
    name: traefik_backend

services:
  # The VPN service (ZeroOne) configuration management tool
  ztncui:
    image: keynetworks/ztncui # The official ztncui docker image
    ports:
      - target: 9993
        published: 9993
        protocol: tcp
        mode: host
    volumes:
      - ./opt/key-networks/ztncui/etc/:/opt/key-networks/ztncui/etc/
      - ./var/lib/zerotier-one/:/var/lib/zerotier-one/
    expose:
      - 3000:3000
    environment:
      HTTPS_PORT: 3000
      HTTP_PORT: 3443
      HTTP_ALL_INTERFACES: "yes"
    cap_add:
      - NET_ADMIN
    labels:
      - "traefik.enable=true"
      - "traefik.port=3443"
      - "traefik.docker.network=traefik_backend"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:zerotier.perlur.cloud"
    networks:
      - traefik_backend
```

as a SWARM deploy config, keys are, bind HTTPS_PORT to 3000, and HTTP port to 3443, because while the script accounts for HTTP access on all interfaces, the Dockerfile does not expose port 3000, and SWARM does not support docker-compose expose overwrites. Container should expose both.

exec.sh should be configured so, that it can be set to "none" and if so, the default value assignment is skipped. Until that is done in the exec.sh, you'll have to also listen on HTTPs, so the workaround is to run the `openssl` commands to create the self-signed certificates as described in the `ztncui` README file. Beware that it looks for `/opt/key-networks/ztncui/etc/tls/fullchain.pem`, not the root tls directory, which is a mess.

I suggest to the developers to expose both ports, that's minimal effort to enable people to actually deploy as a microservice... The evalueation of `exec.sh` imputs should be at least:

IF $HTTP_PORT is set AND $HTTP_ALL_INTERFACES is yes, then do not set $HTTPS_PORT, the user clearly wants to off-load SSL. to the load balancer or whatever. But of course, you can also just create a new $IAMCLEVER=yes, and just execute the $CMD.

Better fix would be to have init.sh which would do all fancy stuff like generate the self-signed certificates themselves, which would run only when working with a fresh vol;ume.
